### ISSUE TITLE
allow local and reference data archives to be passed environment variables

### ISSUE THREAD

**Issue by vpnagraj** [databio/LOLAweb#50]
right now the `cache/`, `universes/`, etc. are hardcoded ... some users developing on the app may not have a local copy of these under their app code structure

we should allow the locations of these to be passed as environment variables at docker run time

**Comment by nmagee** [comment]
Set and use values such as:

```
LWREF='/path/to/reference/root'
LWLOCAL='/path/to/server/files'
```

These should be set either by the user at runtime (setting environment vars for the `docker run` command, or in a Docker compose file. 

They should be consumed within the Shiny app by calling the ENV variable set in the container:

```
lwref = sys.getenv("LWREF")
lwlocal = sys.getenv("LWLOCAL")
```

and then used to set the paths for reference files and local server files.

**Comment by nsheff** [comment]
@vpnagraj what's the status on this? This will be important for my work on #42 and #23

**Comment by nsheff** [comment]
I'm working on this now....

**Comment by nmagee** [comment]
@nsheff just wanting to confirm (my brain is in several places at the moment)...

I'm looking at the ENV variables needed from [here](https://github.com/databio/LOLAweb/blob/dev/apps/LOLAweb/misc.R#L64) and the two variables we need to pass into the swarm config are these, correct?:

```
LWREF = "/mnt/q/shefflab/LOLAweb/"
LWLOCAL = "/data/lola/"
```

**Comment by nmagee** [comment]
I have DEV updated with this config -- sample results work fine, but running sample data does not, throwing a Shiny error. I'm not sure if the second volume mount is correct for retrieving ref data.

'''
  dev:
    [...]
    volumes:
      - /data/lola:/data/lola
      - /mnt/q/shefflab/LOLAweb:/mnt/q/shefflab/LOLAweb/
      - /data/lola/shinylog:/var/log/shiny-server
    environment:
      - LWREF=/mnt/q/shefflab/LOLAweb/
      - LWLOCAL=/data/lola/
    [...]
'''

**Comment by nsheff** [comment]
That looks right. I have broken the sample input independently, I think...

**Comment by nsheff** [comment]
I'm a little confused now though, because the databases are populating correctly, but the "load example data" is not...

and the caches are not being found, either. So, some things are not connecting right.

**Comment by nsheff** [comment]
ls ../cache/F1NJU8KSWI59H4E.RData 
../cache/F1NJU8KSWI59H4E.RData


the example cache is there, but clicking 'sample results' yields `The cache 'F1NJU8KSWI59H4E' does not exist.`

**Comment by nmagee** [comment]
@vpnagraj does the example possibly need to get rebuilt for it to work?

**Comment by nsheff** [comment]
@vpnagraj Pete I think I need you to figure this out... 
for LWREF: databases and universe are working, but examples are not;
for LWLOCAL: shinylogs are working, but caches are not.
not sure why...

**Comment by vpnagraj** [comment]
@nmagee no i don't think we necessarily need to rebuild the cache for it to work here

@nsheff sure i can look into this but i'm currently having issues with ssh on the host machine and can't log on

but as far as the examples go ... i am seeing that in the dropdown for the "Select pre-loaded region set" on dev currently shows all of the reference genome names AND setB_100.bed ... are there sub directories for reference genomes in the `examples/` directory??

and for the caches, my guess is that those are *not* in a directory called `cache/` underneath `/data/lola/` ... i have this working locally too and my `LWREF` variable points to the root of my app directory, directly under which i have a `cache/` folder with all of the caches in it

**Comment by nsheff** [comment]
That cache *is* there on the dev container in the right spot:
 
root@04c531c913a1:/srv/shiny-server# ls /data/lola/cache/F1NJU8KSWI59H4E.RData 
/data/lola/cache/F1NJU8KSWI59H4E.RData

**Comment by nsheff** [comment]
Now the caching is working -- for some reason.  But now loading the setB_100.bed is not working.

>  i am seeing that in the dropdown for the "Select pre-loaded region set" on dev currently shows all of the reference genome names AND setB_100.bed ... are there sub directories for reference genomes in the examples/ directory??
 
I'll start a new issue on that.

**Comment by nsheff** [comment]
I see the problem: 

```
root@e7d898365edc:/mnt/q/shefflab/LOLAweb/examples# cat setB_100.bed 
cat: setB_100.bed: Permission denied
```

Changed permissions and that solved this issue.

**Comment by nsheff** [comment]
ok this is done!

**Comment by vpnagraj** [comment]
awesome have we added a specification for that permission change somewhere in the dockerfile? or did you change that permanently on the host machine?

**Comment by nsheff** [comment]
it was just a misconfiguration of the new project files... so I've made the change permanently in the project space.

**Comment by nsheff** [comment]
By the way, caching is now not working again.
There's something weird going on with the containers.

**Comment by nmagee** [comment]
@nsheff I see you are logged into DEV1. Let me know if it's okay to push all dev containers onto DEV1 -- I will need to `docker service update`, which will kill the two dev containers on DEV2 and launch them onto DEV1. But it should keep the single dev container already on DEV1.

**Comment by nsheff** [comment]
go for it!

**Comment by nmagee** [comment]
This will be implemented fully with v1.2, to roll out today. DEV containers already work under this model, and now have a `docker-compose.yml` file section like this:

```
  dev:
    image: databio/lolaweb:dev
    networks:
      - net
    ports:
      - "80"
    environment:
      - LWREF=$LWREF
      - LWLOCAL=$LWLOCAL
    volumes:
      - ${LWLOCAL}:${LWLOCAL}
      - ${LWREF}:${LWREF}
      - ${LWLOCAL}/shinylog:/var/log/shiny-server
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          memory: 12G
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.docker.network=ssp_net"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefix:/;"
        - "traefik.backend.loadbalancer.sticky=true"
        - "traefik.frontend.rule=Host:dev.lolaweb.databio.org,dev.lolaweb.uvasomrc.io;AddPrefix:/LOLAweb/apps/LOLAweb;"
```
